# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Hyun/soc_proj/Education/1_End/ch12_ps_tftlcd/ch12_ps_tftlcd.srcs/constrs_1/new/top.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_textlcd_0_0/system_textlcd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_textlcd_0_0 || ORIG_REF_NAME==system_textlcd_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_1/system_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_1 || ORIG_REF_NAME==system_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/system/ip/system_pushbutton_0_0/system_pushbutton_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pushbutton_0_0 || ORIG_REF_NAME==system_pushbutton_0_0} -quiet] -quiet

# IP: bd/system/ip/system_TFTLCD_NEW_0_0/system_TFTLCD_NEW_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_TFTLCD_NEW_0_0 || ORIG_REF_NAME==system_TFTLCD_NEW_0_0} -quiet] -quiet

# IP: bd/system/ip/system_seven_seg_0_4/system_seven_seg_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_seven_seg_0_4 || ORIG_REF_NAME==system_seven_seg_0_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
